# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verifiedpublisher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10),
        ),
        migrations.AlterField(
            model_name='verifiedpublisher',
            name='language',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English')], max_length=10),
        ),
    ]
