# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170315_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedpublisher',
            name='name',
            field=models.CharField(default='Publisher1', max_length=100),
            preserve_default=False,
        ),
    ]
