"""
Django settings for storybeep_backend project.

Generated by 'django-admin startproject' using Django 1.10.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

from django.core.exceptions import ImproperlyConfigured
from django.utils.translation import ugettext_lazy as _
from unipath import Path

def get_environment_variable(var_name):
    """ Get the environment variable or return exception """
    try:
        return os.environ[var_name]
    except KeyError:
        error_msg = "Set the %s environment variable" % var_name
        raise ImproperlyConfigured(error_msg)

# Build paths inside the project using Unipath
BASE_DIR = Path(__file__).absolute().ancestor(3)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=5sq-)bnj#85p1r20$0bw2igqw^90^m1@pna4s5a2%8b-$8$c_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pipeline',
    'users',
    'stories',
    'alerts',
    'django.contrib.sites',
    'django_rq',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'storybeep_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.child('templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'storybeep_backend.wsgi.wsgi_base.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# Defining the static files directories

STATICFILES_DIRS = (
    BASE_DIR.child("static"),
)

STATIC_ROOT = BASE_DIR.child("staticfiles")

# django-pipeline settings

STATICFILES_STORAGE = 'pipeline.storage.PipelineStorage'

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "pipeline.finders.PipelineFinder",
    )

PIPELINE = {
    "STYLESHEETS" : {
        "base" : {
            "source_filenames" : (
                "css/base.css",
                ),
            "output_filename" : "css/base.min.css",
            },
        "landing" : {
            "source_filenames" : (
                "css/landing.css",
                ),
            "output_filename" : "css/landing.min.css",
            },
        "home" : {
            "source_filenames" : (
                "css/home.css",
                ),
            "output_filename" : "css/home.min.css",
            },
        "login" : {
            "source_filenames" : (
                "css/vertical_center.css",
                "css/login.css",
                ),
            "output_filename" : "css/login.min.css",
            },
        "signup" : {
            "source_filenames" : (
                "css/vertical_center.css",
                "css/signup.css",
                ),
            "output_filename" : "css/signup.min.css",
            },
        "publisher_home" : {
            "source_filenames" : (
                "css/publisher_home.css",
                ),
            "output_filename" : "css/publisher_home.min.css",
            },
        },
    }


AUTH_USER_MODEL = "users.StorybeepUser"
LOGIN_REDIRECT_URL = "/"


EMAIL_USE_TLS = True
EMAIL_HOST = get_environment_variable("EMAIL_HOST")
EMAIL_PORT = get_environment_variable("EMAIL_PORT")
EMAIL_HOST_USER = get_environment_variable("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = get_environment_variable("EMAIL_HOST_PASSWORD")

MAILER = "mailtest@storybeep.com"

SITE_ID = 4

RQ_QUEUES = {
    "default" : {
        "URL" : os.getenv("REDISTOGO_URL", "redis://localhost:6379"),
        },
}

LOCALE_PATHS = [BASE_DIR.child("locale"),]

LANGUAGES = [
    ('de', _('German')),
    ('en', _('English')),
]
